### ISSUE TITLE
Replace logo and favicon

### ISSUE THREAD

**Issue by carlosms** [smacker/superset-compose#7]
Sources here:
https://github.com/src-d/design/blob/master/media-kit/README.md

**Comment by ricardobaeta** [comment]
@carlosms @smacker The favicon is not listed on the README, but you can find it in https://github.com/src-d/design/tree/master/media-kit/files

![image](https://user-images.githubusercontent.com/1746146/57071606-d8ef3c80-6cd2-11e9-9620-e1e16f3ee210.png)

**Comment by smacker** [comment]
logo was replaced. Favicon is pending.
